// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Products struct {
	ID          uuid.UUID        `json:"id"`
	ProductID   int32            `json:"product_id"`
	Name        string           `json:"name"`
	ProductCode string           `json:"product_code"`
	Description pgtype.Text      `json:"description"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type RiskTypes struct {
	ID           uuid.UUID        `json:"id"`
	RiskTypeID   int32            `json:"risk_type_id"`
	Name         string           `json:"name"`
	RiskCategory string           `json:"risk_category"`
	RiskTypeCode string           `json:"risk_type_code"`
	Description  pgtype.Text      `json:"description"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}
