// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: products.sql

package sqlc

import (
	"context"
)

const createProducts = `-- name: CreateProducts :exec
INSERT INTO products(product_id, name, product_code, description)
 SELECT unnest($1::int[]),unnest($2::text[]),unnest($3::text[]),
        unnest($4::text[]) ON CONFLICT DO NOTHING
`

type CreateProductsParams struct {
	ProductID   []int32  `json:"product_id"`
	Name        []string `json:"name"`
	ProductCode []string `json:"product_code"`
	Description []string `json:"description"`
}

func (q *Queries) CreateProducts(ctx context.Context, arg CreateProductsParams) error {
	_, err := q.db.Exec(ctx, createProducts,
		arg.ProductID,
		arg.Name,
		arg.ProductCode,
		arg.Description,
	)
	return err
}

const createRiskType = `-- name: CreateRiskType :exec
INSERT INTO risk_types(risk_type_id, name, risk_category, risk_type_code, description)
SELECT unnest($1::int[]),unnest($2::text[]),unnest($3::text[]),
       unnest($4::text[]),unnest($5::text[]) ON CONFLICT DO NOTHING
`

type CreateRiskTypeParams struct {
	RiskTypeID   []int32  `json:"risk_type_id"`
	Name         []string `json:"name"`
	RiskCategory []string `json:"risk_category"`
	RiskTypeCode []string `json:"risk_type_code"`
	Description  []string `json:"description"`
}

func (q *Queries) CreateRiskType(ctx context.Context, arg CreateRiskTypeParams) error {
	_, err := q.db.Exec(ctx, createRiskType,
		arg.RiskTypeID,
		arg.Name,
		arg.RiskCategory,
		arg.RiskTypeCode,
		arg.Description,
	)
	return err
}

const getProducts = `-- name: GetProducts :many
SELECT id, product_id, name, product_code, description, created_at FROM products
`

func (q *Queries) GetProducts(ctx context.Context) ([]Products, error) {
	rows, err := q.db.Query(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Products{}
	for rows.Next() {
		var i Products
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Name,
			&i.ProductCode,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRiskType = `-- name: GetRiskType :many
SELECT id, risk_type_id, name, risk_category, risk_type_code, description, created_at FROM risk_types
`

func (q *Queries) GetRiskType(ctx context.Context) ([]RiskTypes, error) {
	rows, err := q.db.Query(ctx, getRiskType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RiskTypes{}
	for rows.Next() {
		var i RiskTypes
		if err := rows.Scan(
			&i.ID,
			&i.RiskTypeID,
			&i.Name,
			&i.RiskCategory,
			&i.RiskTypeCode,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
