// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateProducts(ctx context.Context, arg CreateProductsParams) error
	CreateRiskType(ctx context.Context, arg CreateRiskTypeParams) error
	GetProducts(ctx context.Context) ([]Products, error)
	GetRiskType(ctx context.Context) ([]RiskTypes, error)
}

var _ Querier = (*Queries)(nil)
